server:
  port: 10087

spring:
  application:
    name: hystrixorder10087

eureka:
  instance:
    instance-id: hystrixorder10087 #处理在eureka中的显示
  client:
    register-with-eureka: true #注册到注册中心
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

feign:
  circuitbreaker:
    enabled: true    #开启服务降级
